// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativePostTest.CreatePost_Unauthorized(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativePostTest.CreatePost_WithExistingData_UnprocessableEntity(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativePostTest.CreatePost_WithInvalidData_ReturnsUnprocessableEntity(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativePostTest.DeletePost_Unauthorized_ReturnsNotFound(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativePostTest.GetPost_Unauthorized_ReturnsNotFound(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativePostTest.PartiallyUpdatePost_Unauthorized_ReturnsNotFound(Test.Common.TestData.PatchPostTestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativePostTest.PartiallyUpdatePost_WithInvalidData_ReturnsUnprocessableEntity(Test.Common.TestData.PatchPostTestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativePostTest.UpdatePost_Unauthorized_ReturnsNotFound(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativePostTest.UpdatePost_WithInvalidData_ReturnsUnprocessableEntity(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.CreateUser_Unauthorized(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.CreateUser_WithExistingData_UnprocessableEntity(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.CreateUser_WithInvalidData_ReturnsUnprocessableEntity(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.DeleteUser_Unauthorized(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.GetUser_Unauthorized(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.PartiallyUpdateUser_Unauthorized_ReturnsNotFound(Test.Common.TestData.PatchUserTestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.PartiallyUpdateUser_WithExistingData_UnprocessableEntity(Test.Common.TestData.PatchUserTestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.PartiallyUpdateUser_WithInvalidData_ReturnsUnprocessableEntity(Test.Common.TestData.PatchUserTestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.UpdateUser_Unauthorized_ReturnsNotFound(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.UpdateUser_WithExistingData_UnprocessableEntity(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Negative.NegativeUserTest.UpdateUser_WithInvalidData_ReturnsUnprocessableEntity(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.CommentTest.GetComment_ById(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.CommentTest.GetComments_ByParam_ReturnOneExactComment(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.CommentTest.GetComments_FromPage~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.ComplexTest.Create21UniqueComment_FindCommentAndCheckMetaData_Successful(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.ComplexTest.Create21UniquePost_FindPostAndCheckMetaData_Successful(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.PostsTest.GetPost_ById(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.PostsTest.GetPosts_ByParam_ReturnOneExactPost(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.PostsTest.GetPosts_FromPage~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.UsersTest.GetUser_ById(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.UsersTest.GetUsers_ByParam_ReturnOneExactUser(Test.Common.TestData.TestData)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Naming", "CA1707:Идентификаторы не должны содержать символы подчеркивания", Justification = "<Ожидание>", Scope = "member", Target = "~M:Tests.Integration.Tests.Positive.UsersTest.GetUsers_FromPage~System.Threading.Tasks.Task")]
